### ISSUE TITLE
What's the License?

### ISSUE THREAD

**Issue by 38leinaD** [dcm4che/WarpUnit#4]
I would like to use this library in a corporate project, unfortunately, I am only allowed to do so if the project has a license.
Could we add a permissive license to the repository?
CC @rawmahn @hczedik

**Comment by rawmahn** [comment]
hi Daniel!

I can't say anything for Agfa since I don't work there anymore, however you
are not the only one who wanted to use it in a corporate project.

Some guys here in Vienna actually got inspired by it and went on to
implement their own test framework with a similar concept:
https://github.com/CheetUnit/CheetUnit

It has a proper Apache 2.0 license, more features, and it's in active
development. AFAIK they are using it quite heavily for their enterprise
projects. A week ago they just released an RC version to maven central
https://search.maven.org/search?q=cheetunit

They still have to get the docs right (who doesn't lol), but they've got
lots of examples and tests. So I'd definitely recommend you to have a look
at it if you found WarpUnit useful.

cheers,
Roman.

**Comment by patholzer** [comment]
Hi,

[CheetUnit's docs](https://cheetunit.github.io/CheetUnit/) has now finished. 

@38leinaD We would appreciate to have you as a CheetUnit user. 
If you have any questions or if you need support for setting CheetUnit up, feel free to ask. Every feedback is welcome. 

Cheers,
Patrick and the CheetUnit team
